package:
   name: intake-mnist-data
   version: 0.0.1

source:
   path: ..
git:
  depth: false

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - intake>=0.2
    - python
    - numpy

about:
  home: https://github.com/ContinuumIO/intake
  license: BSD
  license_file: LICENSE
  summary: |
    MNIST digits data and plugin for Intake
